name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Docker image
        run: docker build -t myapp ./web-api
      - name: Start Docker container
        run: docker run -d --name myapp-container --network host myapp
      - name: Install dependencies
        run: npm ci
        working-directory: ./qa
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./qa
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./qa
      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop myapp-container
          docker rm myapp-container
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./qa/playwright-report/
          retention-days: 30
